global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'my_targets'
    static_configs:
      - targets:
          - localhost:8030
          - localhost:12345

rule_files:
  - "rule/alerts.yml"
  - "rule/recording_rule.yml"

alerting:
  alertmanagers:
  - scheme: http
    basic_auth:
      username: "admin"
      password: "password"
  - static_configs:
    - targets:
       - localhost:9093


